// Code generated by goctl. DO NOT EDIT.
package login

type CodeResponse struct {
	Id    string `json:"id"`    // 在登录时提交
	Image string `json:"image"` // 验证码 base64 格式
}

type LoginRequest struct {
	Username string `json:"username" binding:"required" label:"用户名"`      // 用户名
	Password string `json:"password" binding:"required,min=6" label:"密码"` // 密码
	Code     string `json:"code" binding:"required,len=4" label:"验证码"`    // 验证码
	CodeId   string `json:"codeId" binding:"required" label:"获取验证码时的ID"`  // 获取验证码时的ID
}

type LoginResponse struct {
	Jwt string `json:"jwt"` // jwt 凭证
}
