// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameAdminUserModel = "admin_user"

// AdminUserModel mapped from table <admin_user>
type AdminUserModel struct {
	ID        int            `gorm:"column:id;primaryKey;autoIncrement:true"`
	Username  string         `gorm:"column:username"` // 用户名
	Realname  string         `gorm:"column:realname"` // 真实姓名
	Password  string         `gorm:"column:password"` // 密码
	Phone     string         `gorm:"column:phone"`    // 手机号
	RoleID    int            `gorm:"column:role_id"`  // 角色ID
	Status    int            `gorm:"column:status"`   // 状态 0:未启用 1:正常
	CreatedAt time.Time      `gorm:"column:created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at"`
}

// TableName AdminUserModel's table name
func (*AdminUserModel) TableName() string {
	return TableNameAdminUserModel
}
