// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameAdminAuthModel = "admin_auth"

// AdminAuthModel mapped from table <admin_auth>
type AdminAuthModel struct {
	ID         int            `gorm:"column:id;primaryKey;autoIncrement:true"`
	Pid        int            `gorm:"column:pid"`     // 上级ID
	Name       string         `gorm:"column:name"`    // 节点名
	Key        string         `gorm:"column:key"`     // 权限标识
	IsMenu     int            `gorm:"column:is_menu"` // 是否是菜单栏 0：否 1：是
	API        string         `gorm:"column:api"`     // 接口
	Action     string         `gorm:"column:action"`  // 操作方法
	CreateTime time.Time      `gorm:"column:create_time;default:CURRENT_TIMESTAMP"`
	UpdateTime time.Time      `gorm:"column:update_time;default:CURRENT_TIMESTAMP"`
	DeleteTime gorm.DeletedAt `gorm:"column:delete_time"`
}

// TableName AdminAuthModel's table name
func (*AdminAuthModel) TableName() string {
	return TableNameAdminAuthModel
}
