// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameAdminRoleModel = "admin_role"

// AdminRoleModel mapped from table <admin_role>
type AdminRoleModel struct {
	ID         int            `gorm:"column:id;primaryKey;autoIncrement:true"`
	Name       string         `gorm:"column:name"` // 角色名
	Auth       string         `gorm:"column:auth"` // 权限ID
	CreateTime time.Time      `gorm:"column:create_time;default:CURRENT_TIMESTAMP"`
	UpdateTime time.Time      `gorm:"column:update_time;default:CURRENT_TIMESTAMP"`
	DeleteTime gorm.DeletedAt `gorm:"column:delete_time"`
}

// TableName AdminRoleModel's table name
func (*AdminRoleModel) TableName() string {
	return TableNameAdminRoleModel
}
