// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameAuthModel = "auth"

// AuthModel mapped from table <auth>
type AuthModel struct {
	ID        int            `gorm:"column:id;primaryKey;autoIncrement:true"`
	Pid       int            `gorm:"column:pid"`     // 上级ID
	Name      string         `gorm:"column:name"`    // 节点名
	Key       string         `gorm:"column:key"`     // 权限标识
	IsMenu    int            `gorm:"column:is_menu"` // 是否是菜单栏 0：否 1：是
	API       string         `gorm:"column:api"`     // 接口
	Action    string         `gorm:"column:action"`  // 操作方法
	CreatedAt time.Time      `gorm:"column:created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at"`
}

// TableName AuthModel's table name
func (*AuthModel) TableName() string {
	return TableNameAuthModel
}
