// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameRoleModel = "role"

// RoleModel mapped from table <role>
type RoleModel struct {
	ID        int            `gorm:"column:id;primaryKey;autoIncrement:true"`
	Name      string         `gorm:"column:name"` // 角色名
	Auth      string         `gorm:"column:auth"` // 权限ID
	CreatedAt time.Time      `gorm:"column:created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at"`
}

// TableName RoleModel's table name
func (*RoleModel) TableName() string {
	return TableNameRoleModel
}
