// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameRoleModel = "role"

// RoleModel mapped from table <role>
type RoleModel struct {
	ID         int            `gorm:"column:id;primaryKey;autoIncrement:true"`
	Name       string         `gorm:"column:name"` // 角色名
	Auth       string         `gorm:"column:auth"` // 权限ID
	CreateTime time.Time      `gorm:"column:create_time;default:CURRENT_TIMESTAMP"`
	UpdateTime time.Time      `gorm:"column:update_time;default:CURRENT_TIMESTAMP"`
	DeleteTime gorm.DeletedAt `gorm:"column:delete_time"`
}

// TableName RoleModel's table name
func (*RoleModel) TableName() string {
	return TableNameRoleModel
}
