// Code generated by goctl. DO NOT EDIT.
package login

import (
	"go-admin-template/handler/admin/login"

	"github.com/gin-gonic/gin"
)

func RegisterAdminLoginRoute(e *gin.Engine) {
	g := e.Group("")
	g.GET("/code", login.CodeHandle)
	g.POST("/login", login.LoginHandle)
	g.POST("/logout", login.LogoutHandle)
}
