// Code generated by goctl. DO NOT EDIT.
package routes

import (
	"admin_template/routes/admin/auth"
	"admin_template/routes/admin/base"
	"admin_template/routes/admin/login"
	"admin_template/routes/admin/role"
	"admin_template/routes/admin/user"

	"github.com/gin-gonic/gin"
)

func Setup(e *gin.Engine) {
	login.RegisterAdminLoginRoute(e)
	user.RegisterAdminUserRoute(e)
	role.RegisterAdminRoleRoute(e)
	auth.RegisterAdminAuthRoute(e)
	base.RegisterAdminBaseRoute(e)
}
