// Code generated by goctl. DO NOT EDIT.
package routes

import (
	adminAuth "admin_template/routes/admin/auth"
	adminBase "admin_template/routes/admin/base"
	adminLogin "admin_template/routes/admin/login"
	adminRole "admin_template/routes/admin/role"
	adminUser "admin_template/routes/admin/user"

	"github.com/gin-gonic/gin"
)

func Setup(e *gin.Engine) {
	adminLogin.RegisterAdminLoginRoute(e)
	adminUser.RegisterAdminUserRoute(e)
	adminRole.RegisterAdminRoleRoute(e)
	adminAuth.RegisterAdminAuthRoute(e)
	adminBase.RegisterAdminBaseRoute(e)
}
