// Code generated by goctl.DO NOT EDIT.
package user

import (
"admin_template/handler/admin/user"
"admin_template/middleware"

"github.com/gin-gonic/gin"
)

func RegisterAdminUserRoute(e *gin.Engine) {
g := e.Group("")
g.Use(middleware.JwtMiddleware, middleware.AuthMiddleware)
g.GET("/user", user.ListHandle)
g.GET("/user/:id", user.DetailHandle)
g.POST("/user", user.AddHandle)
g.PUT("/user/:id", user.EditHandle)
g.DELETE("/user/:id", user.DelHandle)

}
