// Code generated by goctl. DO NOT EDIT.
package user

import (
	"go-admin-template/handler/admin/user"
	"go-admin-template/middleware"

	"github.com/gin-gonic/gin"
)

func RegisterAdminUserRoute(e *gin.Engine) {
	g := e.Group("")
	g.Use(middleware.JwtMiddleware, middleware.AuthMiddleware)
	g.GET("/admin/user", user.ListHandle)
	g.POST("/admin/user", user.AddHandle)
	g.PUT("/admin/user/:id", user.EditHandle)
	g.DELETE("/admin/user/:id", user.DelHandle)
}
