// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q               = new(Query)
	AdminUserModel  *adminUserModel
	AuthModel       *authModel
	CasbinRuleModel *casbinRuleModel
	RoleModel       *roleModel
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	AdminUserModel = &Q.AdminUserModel
	AuthModel = &Q.AuthModel
	CasbinRuleModel = &Q.CasbinRuleModel
	RoleModel = &Q.RoleModel
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:              db,
		AdminUserModel:  newAdminUserModel(db, opts...),
		AuthModel:       newAuthModel(db, opts...),
		CasbinRuleModel: newCasbinRuleModel(db, opts...),
		RoleModel:       newRoleModel(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	AdminUserModel  adminUserModel
	AuthModel       authModel
	CasbinRuleModel casbinRuleModel
	RoleModel       roleModel
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:              db,
		AdminUserModel:  q.AdminUserModel.clone(db),
		AuthModel:       q.AuthModel.clone(db),
		CasbinRuleModel: q.CasbinRuleModel.clone(db),
		RoleModel:       q.RoleModel.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:              db,
		AdminUserModel:  q.AdminUserModel.replaceDB(db),
		AuthModel:       q.AuthModel.replaceDB(db),
		CasbinRuleModel: q.CasbinRuleModel.replaceDB(db),
		RoleModel:       q.RoleModel.replaceDB(db),
	}
}

type queryCtx struct {
	AdminUserModel  IAdminUserModelDo
	AuthModel       IAuthModelDo
	CasbinRuleModel ICasbinRuleModelDo
	RoleModel       IRoleModelDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		AdminUserModel:  q.AdminUserModel.WithContext(ctx),
		AuthModel:       q.AuthModel.WithContext(ctx),
		CasbinRuleModel: q.CasbinRuleModel.WithContext(ctx),
		RoleModel:       q.RoleModel.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	return &QueryTx{q.clone(q.db.Begin(opts...))}
}

type QueryTx struct{ *Query }

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
