// Code generated by goctl. DO NOT EDIT.
package role

import (
	"admin_template/handler/admin/role"
	"admin_template/middleware"

	"github.com/gin-gonic/gin"
)

func RegisterAdminRoleRoute(e *gin.Engine) {
	g := e.Group("")
	g.Use(middleware.JwtMiddleware, middleware.AuthMiddleware)
	g.GET("/role", role.ListHandle)
	g.GET("/role/:id", role.DetailHandle)
	g.POST("/role", role.AddHandle)
	g.PUT("/role/:id", role.EditHandle)
	g.DELETE("/role/:id", role.DelHandle)

}
